Initial commit for Rust powered modules
fox-it/dissect.util pull request #56
Opened 2024-10-28 19:13 UTC by Schamper

Experimental branch for playing around with Rust powered modules. With this POC I initially set out to replace the dependencies on the `lz4` and `python-lzo` Python dependencies, and replacing them with a Rust powered extension.

The concept here is that we will use `maturin` to build wheels that contain the Rust compiled extension, but we will __not__ change the build system in `pyproject.toml`. This is to ensure that we will never compile when installing a "source wheel". Instead, we will continue to use `tox -e build` to build Python-only wheels, and in parallel build Rust wheels with `maturin`. The theory here being that on a `pip install`, the following will happen:

- On a "blessed" platform (that we build wheels for in our CI), you will automatically enjoy a Rust-powered version
- On a "incompatible" platform (that we don't build wheels for, e.g. a new Python version), you will install the Python-only wheel and automatically enjoy the Python fallback

Play along at home:
```bash
maturin develop
```

Next steps:

- [ ] Test if the wheel made by `maturin build` contains the same stuff as our Python wheel
- [ ] Add build step to CI
- [ ] Add type hints

2025-04-22 15:48 UTC, Schamper commented
I've added CI and replaced `maturin` with plain `setuptools-rust`. I've gone the route of not having `setuptools-rust` in the build dependencies, and adding it manually in the CI. This seems to be the simplest way to achieve what we want.

2025-04-24 07:15 UTC, Schamper commented
I've made another tweak and that's to use an intree build backend as described in PEP517 and here: https://setuptools.pypa.io/en/latest/build_meta.html#dynamic-build-dependencies-and-other-build-meta-tweaks

2025-06-02 15:27 UTC, twiggler requested changes
Preliminary review.

Nice experiment.

2025-06-02 15:27 UTC, twiggler commented on dissect/util/_build.py
> +from __future__ import annotations
Works. 

Have  not found a better solution yet :).

2025-06-03 07:52 UTC, Schamper commented on dissect/util/_native.src/src/compression/lz4.rs
> +        let mut output_size = lz4_flex::block::get_maximum_output_size(src.len());
Applied.

2025-06-12 10:44 UTC, twiggler requested changes

2025-06-12 10:44 UTC, twiggler commented on dissect/util/_native.src/src/compression/lzo.rs
> +        )
```suggestion
        (src, (buflen >= 0).then_some(buflen as usize))
```

(untested)

2025-06-12 10:44 UTC, twiggler commented on dissect/util/_native.src/src/compression/lzo.rs
>              return Err(PyErr::new::<PyValueError, _>(
```suggestion
            return Err(PyValueError::new_err("Invalid header value"));
```

(untested)

2025-06-16 07:57 UTC, twiggler approved these changes

2025-06-25 14:50 UTC, merged